# monitor/Dockerfile
FROM python:3.11-slim

WORKDIR /app

# Копируем зависимости
COPY monitor/requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Копируем весь код в образ
COPY shared/ ./shared/
COPY core/ ./core/
COPY monitor/ ./monitor/

# Настройка окружения
ENV PYTHONPATH=/app
ENV PYTHONUNBUFFERED=1

# Запуск монитора
CMD ["python", "monitor/file_monitor.py"]